var fingering = {
  "C":  [{ "position":"1-3", "finger":3}],
  "Am": [{ "position":"4-2", "finger":2}],
  "F":  [{ "position":"2-1", "finger":1},
         { "position":"4-2", "finger":2}],
  "G":  [{ "position":"1-2", "finger":2},
         { "position":"2-3", "finger":3},
         { "position":"3-2", "finger":1}],
  "Em": [{ "position":"1-2", "finger":1},
         { "position":"2-3", "finger":2},
         { "position":"3-4", "finger":3}],
  "G7": [{ "position":"1-2", "finger":3},
         { "position":"2-1", "finger":1},
         { "position":"3-2", "finger":2}],
  "Fm": [{ "position":"1-3", "finger":4},
         { "position":"2-1", "finger":2},
         { "position":"4-1", "finger":1}],
  "D":  [{ "position":"2-2", "finger":3},
         { "position":"3-2", "finger":2},
         { "position":"4-2", "finger":1}],
  "D7": [{ "position":"1-3", "finger":2},
         { "position":"2-2", "finger":1},
         { "position":"3-2", "finger":1},
         { "position":"4-2", "finger":1}],
  "Gsus4": [{ "position":"1-3", "finger":4},
         { "position":"2-3", "finger":3},
         { "position":"3-2", "finger":2}],

}